### ISSUE TITLE
Jar files have incorrect location for java.sql.Driver

### ISSUE THREAD

**Issue by tsegall** [DataGrip/mongo-jdbc-driver#11]
The jar files created by the build script have java.sql.Driver in the jar/META-INF/services directory.  As per the JDBC 4.2 specification (https://download.oracle.com/otn-pub/jcp/jdbc-4_2-mrel2-spec/jdbc4.2-fr-spec.pdf?AuthParam=1592503219_c759451c5b8cba86fa4a5e42f2c84cc6) section 9.2.1 Loading a driver that implements java.sql.Driver

"JDBC 4.0 Drivers must include the file META-INF/services/java.sql.Driver. "

So this file should be in META-INF/services/java.sql.Driver and not jar/META-INF/services .

As it stands we need to unjar the archive, move the files, and then rejar to use this driver.

Thoughts?

**Comment by kornilova203** [comment]
Thank you
Fixed by e8502d7cd2763293d841c0b14f25430ff22baabd
