### ISSUE TITLE
The official JDBC driver for mongoDb has come out, version 1.0.0,has  plan to  integrated ?

### ISSUE THREAD

**Issue by helpta** [DataGrip/mongo-jdbc-driver#12]
The official JDBC driver for mongoDb has come out, version 1.0.0, is there any consideration for integrated use?

**Comment by chenjienn** [comment]
> The official JDBC driver for mongoDb has come out, version 1.0.0, is there any consideration for integrated use?

Hi~  actually i can not find official JDBC driver for mongoDB, could you provide the web site?

**Comment by helpta** [comment]
I found the document here:
https://docs.mongodb.com/datalake/tutorial/jdbc-driver

'jdbc jar'  can download from maven repo:
https://mvnrepository.com/artifact/org.mongodb/mongodb-jdbc

although it's not customization for java application , but it's a signal. And, I have tried, but it's not worked ,just notice me 'namespace is not correct '

you can use this test case (or you can write it by yourself)
`

public class MongoDBTest {

    public static void main(String[] args) throws Exception {
        MongoDriver registeredDriver = new MongoDriver();
        DriverManager.registerDriver(registeredDriver);
        java.util.Properties info = new java.util.Properties();
        info.put("user", "demoUserName");
        info.put("password", "demoPsw");
        info.put("database", "schemaName");

        Connection conn = DriverManager.getConnection("jdbc:mongodb://127.0.0.1:27017/schemaName", info);
        Statement statement = conn.createStatement();
        statement.setFetchSize(10);
        ResultSet resultSet = statement.executeQuery("db.someCollection.find().limit(5)");
        syso(resultSet);
    }

    private static void syso(ResultSet resultSet) throws SQLException {
        ResultSetMetaData metaData = resultSet.getMetaData();
        int columnCount = metaData.getColumnCount();

        while (resultSet.next()) {
            for (int i = 1; i <= columnCount; i++) {
                System.err.println(metaData.getColumnLabel(i) + "===" + JSONUtil.toJson(resultSet.getObject(i)));
            }
        }
    }

}
`

**Comment by kornilova203** [comment]
Hello everyone,
The driver you linked is **MongoDB Data Lake** driver. It uses experimental `sql` feature that is available only for Data Lake
(see https://docs.mongodb.com/datalake/reference/pipeline/sql) therefore you cannot connect to MongoDB database.

You can see here that it simply uses `$sql` aggregation stage:
https://github.com/mongodb/mongo-jdbc-driver/blob/master/src/main/java/com/mongodb/jdbc/MongoStatement.java#L51
So it cannot execute javascript code.

But I guess we can patch our driver such that it uses Data Lake $sql feature.
I also see that driver fetches `INFORMATION_SCHEMA` for meta information. I could try to use it for Data Lake

**Comment by helpta** [comment]
> So it cannot execute javascript code.

 yes.  But I saw the document [the 'Val()' method was deprected.](https://docs.mongodb.com/manual/reference/method/db.eval/)  what we used to execute script.

> Deprecated since version 3.0.
Starting in version 4.2, MongoDB removes the eval command. The deprecated db.eval(), which wraps the eval command, can only be run against MongoDB 4.0 or earlier versions. For behavior and example, refer to the 4.0 or earlier version of the manual.

so, I think there should have a new way to do the same thing.

**Comment by kornilova203** [comment]
We don't use `eval` command.
I created a Java wrapper for [new mongo shell](https://github.com/mongodb-js/mongosh) that delegates calls to official MongoDB Java driver.
We use this wrapper in this JDBC driver

**Comment by helpta** [comment]
ok. my bad. I saw codes like below , that direct me to think we used `eval` command . Hope 'official JDBC driver' come out earlier.


`MongoshScriptEngine#execute
MongoShell repl = this.getRepl();
MongoShellResult<?> result = repl.eval(query);`
