### ISSUE TITLE
When to support ISODate format 'YYmmdd'?

### ISSUE THREAD

**Issue by Cherrymelon** [DataGrip/mongo-jdbc-driver#13]
it's wired that not support 'YYmmdd' format,although support YY-mm-dd now,can make a little step forward?

**Comment by kornilova203** [comment]
I've implemented it in mongosh Java library: https://github.com/mongodb-js/mongosh/pull/544
@Cherrymelon, do you want to build JDBC driver yourself or you use driver provided by JetBrains IDEs?

**Comment by Cherrymelon** [comment]
i'm confused about diff between mongo-jdbc-driver and mongosh,it seems too long to make update about mongo-jdbc-driver repo?i use JetBrains IDE

**Comment by kornilova203** [comment]
@Cherrymelon,
Sorry for slow reply
`mongo-jdbc-driver` embeds `mongosh` to execute commands.
This commit will go to the next `mongo-jdbc-driver` and update will be available in IDE (I cannot tell now when it happens, I haven't planed it yet)

**Comment by kornilova203** [comment]
@Cherrymelon,
I forgot to tell you that couple of weeks ago I uploaded new driver with this feature
You may update it on datasource page:
<img width="800" alt="Screenshot 2021-02-10 at 17 51 35" src="https://user-images.githubusercontent.com/23450724/107526214-ae7d2380-6bc8-11eb-8498-348c945c11a0.png">
