### ISSUE TITLE
Update java shell version to support MONGO-AWS auth mechanism (MongoDB version >=4.4)

### ISSUE THREAD

**Issue by sdushay** [DataGrip/mongo-jdbc-driver#14]
Hey there--
Our team wants to use datagrip to interact with a mongo atlas database using the authentication mechanism described here: https://docs.mongodb.com/drivers/node/fundamentals/authentication/mechanisms#mongodb-aws, which is only supported by MongoDB version >= 4.4, which I gather means shell version >=4.4 as well.

It looks like `mongosh` (https://github.com/mongodb-js/mongosh) supports this feature, with the added requirement of aws4 (https://www.npmjs.com/package/aws4), but I can see that the forked version of mongosh, (https://github.com/kornilova203/mongosh) is stuck at v0.3, whereas the original is up to 0.7.7 https://github.com/mongodb-js/mongosh/releases/tag/v0.7.7  Is there any chance of using the original version to back this driver, or updating the fork any time soon?

**Comment by kornilova203** [comment]
Hello @sdushay,
_java-mongosh_ version does not correspond to _mongosh_ version.
So the fork https://github.com/kornilova203/mongosh is up-to-date with original repo.

BUT the _java-mongosh_ uses old MongoDB Java driver v3.12.7
I need to update it to 4.2.0 then it will be possible to specify `authMechanism=MONGODB-AWS` in connection string.

Let's see if I can quickly do it...

**Comment by kornilova203** [comment]
PR with driver update: https://github.com/mongodb-js/mongosh/pull/636
Tomorrow I also want to fix this one: https://youtrack.jetbrains.com/issue/DBE-12537
Then I'll run DataGrip tests with new driver and you'll be able to download it on Friday or in the beginning of next week.

**Comment by kornilova203** [comment]
Hello @sdushay,
We released new driver. You may click on `Update driver` on Data Source config page.
It now accepts connection string with `MONGODB-AWS` auth mechanism

<img width="800" alt="Screenshot 2021-02-15 at 13 44 07" src="https://user-images.githubusercontent.com/23450724/107936750-0edadf00-6f94-11eb-9002-d025e4ea4f01.png">

**Comment by sdushay** [comment]
@kornilova203 Awesome! Thanks so much for the quick work!
