### ISSUE TITLE
Implement collection.deleteMany in ui view

### ISSUE THREAD

**Issue by RedcodesDev** [DataGrip/mongo-jdbc-driver#19]
I would like to suggest implementing the deleteMany function if you delete more than one document via the ui collection view.

If you currently wish to delete more than one document, Datagrip will go through every single document and call deleteOne on it. It would be more efficient to use deleteMany one time and delete every single document selected. An example deleteMany command would be:
```
db.getCollection("testCollection").deleteMany({ $or: [ {
   _id: new ObjectId("6220db3d9362dd2bc1a86096"),
   _id: new ObjectId("6220db409362dd2bc1a860c5")
 } ] } );
```

Datagrip would just need to get all the _id fields of the selected documents and call the deleteMany method once. It currently takes about 45s to delete 100 documents, and this could be very much decreased by deleting all at once.

**Comment by kornilova203** [comment]
@RedcodesDev, thanks!
That's a good idea
We already have this request in DataGrip bug tracker.
Please upvote here - https://youtrack.jetbrains.com/issue/DBE-13680

I'll close this issue because it's not related to the driver itself
