### ISSUE TITLE
User management method does not work.

### ISSUE THREAD

**Issue by hangum** [DataGrip/mongo-jdbc-driver#5]
User management method does not work.

These are the instructions below.
https://docs.mongodb.com/manual/reference/method/js-user-management/
thanks.

Name | Description
db.auth() | Authenticates a user to a database.
db.changeUserPassword() | Changes an existing user’s password.
db.createUser() | Creates a new user.
db.dropUser() | Removes a single user.
db.dropAllUsers() | Deletes all users associated with a database.
db.getUser() | Returns information about the specified user.
db.getUsers() | Returns information about all users associated with a database.
db.grantRolesToUser() | Grants a role and its privileges to a user.
db.removeUser() | Deprecated. Removes a user from a database.
db.revokeRolesFromUser() | Removes a role from a user.
db.updateUser() | Updates user data.
passwordPrompt() | Prompts for the password as an alternative to specifying passwords directly in various mongo shell user authentication/management methods.

**Comment by kornilova203** [comment]
Hello @hangum,
This is a know issue
See https://youtrack.jetbrains.com/issue/DBE-9645

But I started to implement [mongodb-js/mongosh](https://github.com/mongodb-js/mongosh) for Java and soon this problem will be resolved

**Comment by kornilova203** [comment]
Current state:
`db.auth()` is not implemented
other methods seem to be implemented but I didn't check all of them

**Comment by hangum** [comment]
@kornilova203  Thanks a lot.
